### ISSUE TITLE
MnS_Exp 1.1.4  - forge 28.0.45+

### ISSUE THREAD

**Issue by LimeTheOn** [TheRealM18/Mine-And-Slash---Expansion#2]
You might have did it this way for a good reason in which case forget I bothered you at all but currently yours the only mod that had any problem when I updated and its 99% just because you made it require "forge_ver" instead of "forge_ver or above". If theres no specific reason for that could you make it in the future use that method?

Thank you for your time!

**Comment by TheRealM18** [comment]
what is the version of forge you are using,  I want to look into it, but it should except 28.0.45 and above.  I can't double check it if i do not know what version your currently on.

**Comment by LimeTheOn** [comment]
28.0.49 is the version where I've encountered the msg saying yours only accepts 28.0.45, sorry should have said that earlier

**Comment by TheRealM18** [comment]
Ok I'll look into it, when my power gets back on.  I might be able to do it, maybe from my phone maybe.

**Comment by TheRealM18** [comment]
SHould be fixed in the latest Release now.

**Comment by LimeTheOn** [comment]
Confirmed fixed, good stuff! Thank you! :)
